# Generated by Django 5.2 on 2025-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Digital Arts', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='digital_art_img/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flyer', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='flyer_img/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Logos', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='logos_img/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCoverArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Music Cover Arts', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='music_cover_art_img/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
