# Generated by Django 5.2 on 2025-04-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_digitalart_flyer_logo_musiccoverart'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalart',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musiccoverart',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
